name: Deploy Laravel to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e

            cd ${{ vars.PROJECT_PATH }}

            echo "Sync repository..."
            git fetch origin
            git reset --hard origin/main
            git clean -fd


            echo "Generate .env..."


            printf "APP_NAME=\"%s\"\n" "${{ vars.APP_NAME }}" > .env
            printf "APP_ENV=%s\n" "${{ vars.APP_ENV }}" >> .env
            printf "APP_KEY=%s\n" "${{ secrets.APP_KEY }}" >> .env
            printf "APP_DEBUG=false\n" >> .env
            printf "APP_URL=%s\n\n" "${{ vars.APP_URL }}" >> .env

            printf "DB_CONNECTION=mysql\n" >> .env
            printf "DB_HOST=%s\n" "${{ vars.DB_HOST }}" >> .env
            printf "DB_PORT=3306\n" >> .env
            printf "DB_DATABASE=%s\n" "${{ vars.DB_DATABASE }}" >> .env
            printf "DB_USERNAME=%s\n" "${{ vars.DB_USERNAME }}" >> .env
            printf "DB_PASSWORD=%s\n\n" "${{ secrets.DB_PASSWORD }}" >> .env

            printf "CACHE_DRIVER=file\n" >> .env
            printf "QUEUE_CONNECTION=sync\n" >> .env
            printf "SESSION_DRIVER=file\n" >> .env
            printf "SESSION_LIFETIME=120\n" >> .env


            echo "Install Composer..."
            composer install --optimize-autoloader --no-interaction

            echo "Install Node..."
            npm ci


            echo "Build Assets..."
            rm -rf public/build
            npm run build

            echo "Optimize Laravel..."
            php artisan config:clear
            php artisan cache:clear
            php artisan route:clear
            php artisan view:clear

            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo "Fix ownership..."
            # ggmu DIGANTI DENGAN USERNAME VPS YANG KELEN GUNAKAN
            sudo chown -R ggmu:www-data ${{ vars.PROJECT_PATH }}

            echo "Fix permissions..."
            sudo chmod -R 775 storage bootstrap/cache
            sudo chmod -R g+s storage bootstrap/cache

            echo "Restart PHP..."
            sudo systemctl reload php8.2-fpm

            echo "Restart NGINX..."
            sudo systemctl reload nginx

            echo "Deploy selesai!!!"
