name: Deploy Laravel to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            script: |
            set -e

              cd ${{ vars.PROJECT_PATH }}
            
              echo "Pull latest code..."
              git pull origin main
            
              echo "Generate .env..."
              cat > .env <<EOF
              APP_NAME="${{ vars.APP_NAME }}"
              APP_ENV=${{ vars.APP_ENV }}
              APP_KEY=${{ secrets.APP_KEY }}
              APP_DEBUG=false
              APP_URL=${{ vars.APP_URL }}
              
              DB_CONNECTION=mysql
              DB_HOST=${{ vars.DB_HOST }}
              DB_PORT=3306
              DB_DATABASE=${{ vars.DB_DATABASE }}
              DB_USERNAME=${{ vars.DB_USERNAME }}
              DB_PASSWORD=${{ secrets.DB_PASSWORD }}
              
              CACHE_DRIVER=file
              QUEUE_CONNECTION=sync
              SESSION_DRIVER=file
              SESSION_LIFETIME=120
              EOF
            
              echo "Install Composer..."
              rm composer.lock
              composer install --no-dev --optimize-autoloader --no-interaction
            
              echo "Install Node..."
              npm ci
            
              echo "Build Assets..."
              npm run build
            
              echo "Optimize Laravel..."
              php artisan config:clear
              php artisan cache:clear
              php artisan route:clear
              php artisan view:clear
            
              php artisan config:cache
              php artisan route:cache
              php artisan view:cache
            
              echo "Fix ownership..."
              sudo chown -R ggmu:www-data ${{ vars.PROJECT_PATH }}
            
              echo "Fix permissions..."
              sudo chmod -R 775 storage bootstrap/cache
              sudo chmod -R g+s storage bootstrap/cache
            
              echo "Restart PHP..."
              sudo systemctl reload php8.2-fpm
            
              echo "Restart NGINX..."
              sudo systemctl reload nginx
            
              echo "Deploy selesai!!!"
